### ISSUE TITLE
 关于上下级联级

### ISSUE THREAD

**Issue by Kumozawa** [a24211317/easy1400#1]
关于上下级联级的部分作者有没有实现思路或者方案呢？
 以及如何让上下级联级的功能能够满足GA/T1400协议的标准？
求解

**Comment by a24211317** [comment]
级联现在实现了上下级的注册保活和对下级视图库的订阅

**Comment by Kumozawa** [comment]
那这个有满足GA/T1400的协议嘛

**Comment by a24211317** [comment]
满足的呀，都是基于1400协议文档开发的

**Comment by Kumozawa** [comment]
![image](https://github.com/a24211317/easy1400/assets/108660882/2e74d4b1-3915-4402-9e21-614f404e0988)
可以请问一下关于这个的参数需要填写的是哪里的嘛，是需要连接到1400的端口还是可以直连平台端呢？

**Comment by a24211317** [comment]
没太理解你的问题，如果是对接上下级视图库的话这里填写对方视图库的信息，如果对接的ipc的1400不需要在这里添加

**Comment by Kumozawa** [comment]
大佬方便给个微信或者qq交流一下吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月27日(周一) 上午10:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [a24211317/easy1400]  关于上下级联级 (Issue #1)




 
没太理解你的问题，如果是对接上下级视图库的话这里填写对方视图库的信息，如果对接的ipc的1400不需要在这里添加

**Comment by a24211317** [comment]
QQ吧 24211317

**Comment by Kumozawa** [comment]
只找到了一个群聊诶，是加群吗？

**Comment by a24211317** [comment]
![image](https://github.com/a24211317/easy1400/assets/49759199/15a06a02-9f5a-46e9-9348-a874e1d07098)
