### ISSUE TITLE
如何启动后端项目

### ISSUE THREAD

**Issue by DXnima** [a24211317/easy1400#2]
使用idea如何启动项目，idea自动扫描到很多模块, 哪个模块是启动后端项目的
![image](https://github.com/a24211317/easy1400/assets/45487731/af358ec5-70a9-40f2-b6a3-a4bc04cf9f27)
数据库恢复：
quartz.sql和easy1400-data.sql两个sql文件恢复到哪个数据库中

**Comment by a24211317** [comment]
quartz.sql在easy1400-ry
easy1400-data就是easy1400-data库的

后台启动system auth gateway和viid

**Comment by DXnima** [comment]
> quartz.sql在easy1400-ry easy1400-data就是easy1400-data库的
> 
> 后台启动system auth gateway和viid
system auth gateway和viid分别占用一个服务端口吗，启动有先后顺序吗

**Comment by a24211317** [comment]
对 分别会占用端口，启动顺序没要求

**Comment by DXnima** [comment]
> 对 分别会占用端口，启动顺序没要求

修改yml配置都在easy1400-config库的表config_info中修改吗

**Comment by a24211317** [comment]
nacos里修改
nacos链接easy1400-config这个库

**Comment by DXnima** [comment]
> nacos里修改 nacos链接easy1400-config这个库

你好，nacos在哪里修改是每个yml文件里，还是数据库哪个表
